CREATE TABLE wishlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE wishlist IS 'Stores user wishlist submissions.';
COMMENT ON COLUMN wishlist.name IS 'Name of the user.';
COMMENT ON COLUMN wishlist.email IS 'Email address of the user, must be unique.';
COMMENT ON COLUMN wishlist.created_at IS 'Timestamp of when the wishlist entry was created.'; 